name: discord-integration
author: tadeu
version: '${project.version}'
depend: [ LuckPerms ]
softdepend: [ Vault ]
main: com.github.zyypj.discordintegration.TokenPlugin
api-version: '1.21'
commands:
  vincular:
    description: Comando para vincular o Discord ao Minecraft.