name: discord-integration
author: tadeu
version: '1.0'
depends: [ LuckPerms, RoyaleEconomy, AuraSkills ]
main: com.github.zyypj.discordintegration.TokenPlugin
api-version: 1.8
commands:
  vincular:
    description: Comando para vincular o Discord ao Minecraft.